inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - '*.gemspec'
    - 'bin/**'

#################
#  Layout Cops  #
#################

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
  AutoCorrect: true

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HeredocIndentation:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/LineLength:
  Max: 81
  Exclude:
    - Vagrantfile

###############
#  Lint Cops  #
###############

# These are idiomatic
Lint/AssignmentInCondition:
  Enabled: false

##################
#  Metrics Cops  #
##################

Metrics/BlockLength:
  Exclude:
    - Vagrantfile
    - Guardfile
    - '**/*_spec.rb'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 150

#################
#  Naming Cops  #
#################

Naming/MethodParameterName:
  AllowedNames:
    - io
    - fd

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/language_server/common/async_process/handle.rb

################
#  Style Cops  #
################

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  ConsistentQuotesInMultiline: true
  EnforcedStyle: double_quotes

Style/PerlBackrefs:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

################
#  RSpec Cops  #
################

RSpec/FilePath:
  Exclude:
    - spec/language_server/**/*.rb

RSpec/MultipleExpectations:
  Max: 2

#  vim: set ts=8 sw=2 tw=0 ft=yaml et :
